### PR TITLE
4.2.3

### PR DESCRIPTION
**Pull request by dtip**
It looks like the regro-cf-autotick-bot missed this one.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dtip** [comment]
@conda-forge-admin, please rerender.

**Comment by dtip** [comment]
@ocefpaf any idea why the regro-cf-autotick-bot missed this release?

**Comment by ocefpaf** [comment]
> @ocefpaf any idea why the regro-cf-autotick-bot missed this release?

B/c the URL did not change it may have been due to the downtime we had in the past week.

**Comment by dtip** [comment]
Thanks for the info :)

**Pull request merged**
