### PR TITLE
proj.4 -> proj4

### PR DESCRIPTION
**Pull request by kynan**

### CODE REVIEW

**Comment by isuruf** [comment]
You need to do a rerender. https://conda-forge.org/docs/conda_smithy.html#how-to-re-render

**Comment by kynan** [comment]
@ocefpaf @isuruf turns out perl-xml-parser is a build time dependency and that's not available on conda-forge.

**Comment by kynan** [comment]
conda-forge/staged-recipes#3285

**Comment by kynan** [comment]
I'm a bit out of my depth on the Mac and Windows failures here @conda-forge/core

**Comment by ocefpaf** [comment]
Sorry @kynan I don't own a Mac and I am not good with it. We need to check those cmake logs though to see what is going on.

**Comment by kynan** [comment]
Puzzled by the Circle CI failure: seems copying the LICENSE file failed, no idea why that could be. @isuruf @ocefpaf

**Comment by isuruf** [comment]
Probably because the path given in `license_file` entry in the `meta.yaml` is wrong.

**Comment by kynan** [comment]
@isuruf it's not. `LICENSE` is the license file in the tarball.

**Comment by kynan** [comment]
@isuruf @ocefpaf the Mac build failed but I merged regardless, can't delay any longer. Is there any sensible way of testing the Mac build locally?

**Comment by ocefpaf** [comment]
Only if you own a Mac. It is quite complicated to reproduce Travis-CI env exactly, but as long as you check things with conda-inspect you'll know what is being linked from your system.

**Comment by kynan** [comment]
I have access to a Mac. Tried to find instructions for running the Travis build locally but failed. Is there documentation somewhere?

**Comment by ocefpaf** [comment]
> Tried to find instructions for running the Travis build locally but failed.

Do you have `conda` and `conda-build` installed? Then you need to call `conda build recipe` to start a build. I recommend you to add two extra test lines like [theses](https://github.com/conda-forge/nco-feedstock/blob/master/recipe/meta.yaml#L47-L48) so you can watch what is being linked from your system.

**Pull request merged**
