### PR TITLE
Temporarily remove IR as maintainer

### PR DESCRIPTION
**Pull request by iainrussell**
Stephan, perhaps if we do this via 2 pull requests - one to remove me, then one to re-add me?

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dtip** [comment]
@iainrussell It seems that at the moment you're missing from meta.yaml as a maintainer. If you want to add yourself you need to put your github username there. Once you re-render the feedstock then your name will automatically be added to the README. Manually adding yourself to the README (as far as I'm aware) doesn't add you as a maintainer.

@StephanSiemen ^ FYI

**Comment by iainrussell** [comment]
Ah, thanks @dtip ! I'll do that now! I did Google this, but could not find
how to add a maintainer to the list.

**Comment by dtip** [comment]
Happy to help! The documentation can be a bit sparse for conda forge. In general all of the important stuff for a feedstock goes in meta.yaml

**Comment by iainrussell** [comment]
This is no longer needed

**Pull request closed without merging**
